unstable:
  image: debian:unstable
  script:
    - apt-get update
    - apt-get install -y build-essential fakeroot
    - apt-get build-dep -y .
    - dpkg-buildpackage -uc -us -rfakeroot
    - ( set -x; for deb in ../*.deb; do dpkg-deb --info $deb; dpkg-deb --contents $deb; done )
    - ( set -x; dpkg --force-confmiss --force-confnew -i ../*.deb || { apt-get install -fy; dpkg --force-confmiss --force-confnew -i ../*.deb; } )
    - dpkg -l postgresql\* | cat
    - ./cleanpg
    - cd /usr/share/postgresql-common && SKIP_IPV6=1 ./testsuite -v "$(debian/supported-versions)" -i -M

jessie:
  tags:
    - jessie
  script:
    - sudo apt-get update
    - sudo apt-get install -y build-essential fakeroot debhelper libreadline-dev lsb-release dh-systemd
    - dpkg-buildpackage -uc -us -rfakeroot
    - ( set -x; for deb in ../*.deb; do dpkg-deb --info $deb; dpkg-deb --contents $deb; done )
    - ( set -x; sudo dpkg --force-confmiss --force-confnew -i ../*.deb || { sudo apt-get install -fy; sudo dpkg --force-confmiss --force-confnew -i ../*.deb; } )
    - dpkg -l postgresql\* | cat
    - sudo ./cleanpg
    - cd /usr/share/postgresql-common && sudo ./testsuite -v "$(debian/supported-versions)" -i

centos7:
  tags:
    - centos7
  script:
    - sudo yum install -y rpm-build
    - rm -rf $HOME/rpmbuild
    - make rpmremove
    - make rpmbuild
    - rpm -ql pgdg-centos11 > /dev/null || sudo yum install -y https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm
    - make rpminstall
    - sudo ./cleanpg
    - cd /usr/share/postgresql-common && sudo ./testsuite -v "$(debian/supported-versions)" -i
